services:
  bankcards-service:
    build: .
    container_name: bankcards-service
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    networks:
      - bankcards-net
  postgres:
    image: postgres:13.22-alpine3.22
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: bankcards
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - bankcards-net

volumes:
  postgres_data:
networks:
  bankcards-net: